### ISSUE TITLE
Busted, Torch and Travis

### ISSUE THREAD

**Issue by AlexMili** [Olivine-Labs/busted#512]
Hi,

I am trying to use Busted with Torch. It works on my local machine but it's impossible to make it compile on Travis. I tried to delete torch installation from my Travis file and everything works. So, it's Torch installation which messing up with the process.

Here is my travis file:
```yaml
language: c

branches:
  only:
    - master
    - travis
    - specs

sudo: true

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1

before_install:
  - source .travis/setenv_lua.sh
  - travis_wait .travis/install-torch-wrapper.sh $(pwd)/deps/torch $(pwd)/torch-install-log.txt
  - source $(pwd)/deps/torch/install/bin/torch-activate

install:
  - luarocks make torch-dataframe-0.1-1.rockspec CFLAGS="-O2 -fPIC -fprofile-arcs -ftest-coverage" LIBFLAG="-shared"
  - luarocks install csvigo
  - luarocks install luafilesystem
  - luarocks install busted

script:
  - cd specs
  - busted simple_spec.lua

after_success:
  - echo "Tests passed"

notifications:
  email:
    on_success: change
    on_failure: always

```

Here is the error I got :
```bash
$ busted simple_spec.lua

/home/travis/build/AlexMili/torch-dataframe/deps/torch/install/bin/luajit: ...ame/deps/torch/install/share/lua/5.1/luarocks/loader.lua:117: error loading module 'term.core' from file '/home/travis/build/AlexMili/torch-dataframe/deps/torch/install/lib/lua/5.1/term/core.so':

	/home/travis/build/AlexMili/torch-dataframe/deps/torch/install/lib/lua/5.1/term/core.so: undefined symbol: __gcov_merge_add

stack traceback:

	[C]: in function 'a_loader'

	...ame/deps/torch/install/share/lua/5.1/luarocks/loader.lua:117: in function <...ame/deps/torch/install/share/lua/5.1/luarocks/loader.lua:114>

	[C]: in function 'require'

	...dataframe/deps/torch/install/share/lua/5.1/term/init.lua:21: in main chunk

	[C]: in function 'require'

	...frame/deps/torch/install/share/lua/5.1/busted/runner.lua:5: in main chunk

	[C]: in function 'require'

	.../install/lib/luarocks/rocks/busted/2.0.rc11-0/bin/busted:3: in main chunk

	[C]: at 0x00406240
```

For more details see the full travis report :
https://travis-ci.org/AlexMili/torch-dataframe/builds/125953790

And my repo:
https://github.com/AlexMili/torch-dataframe/tree/specs

Am I missing something ?

**Comment by DorianGray** [comment]
I think you're using the normal luarocks whereas torch7 ships with it's own version that uses luajit instead of lua.

**Comment by AlexMili** [comment]
Thank you for your response, I fixed the problem by using ```hererocks``` to install luarocks and only use luarocks afterwards.

Here is a working solution :
```yaml
language: python

sudo: false

branches:
  only:
    - master
    - develop
env:
  global:
    - LUAROCKS=2.3.0
    - TORCH_SERVER=https://raw.githubusercontent.com/torch/rocks/master/
  matrix:
    - LUA="lua 5.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks --from=$TORCH_SERVER install dok
  - luarocks --from=$TORCH_SERVER install torch
  - luarocks --from=$TORCH_SERVER install csvigo
  - luarocks install luafilesystem
  - luarocks install busted
  - luarocks make rocks/torch-dataframe-scm-1.rockspec CFLAGS="-O2 -fPIC -fprofile-arcs -ftest-coverage" LIBFLAG="-shared"

script:
  - cd specs
  - ./run_all.sh

after_success:
  - echo "Tests passed"

notifications:
  email:
    on_success: change
    on_failure: always
```
